# Generated by Django 3.0.3 on 2020-02-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_v020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscheduletrigger',
            name='frequency',
            field=models.CharField(choices=[('MIN', 'Minute'), ('HOU', 'Hour'), ('DAY', 'Day'), ('WEE', 'Week'), ('MON', 'Month'), ('FDD', 'First Day'), ('FWK', 'First Week Day'), ('FWD', 'First Weekend Day'), ('LDD', 'Last Day'), ('LWK', 'Last Week Day'), ('LWD', 'Last Weekend Day')], help_text='Specify the frequency of the trigger.', max_length=3),
        ),
        migrations.AlterField(
            model_name='scheduletrigger',
            name='frequency',
            field=models.CharField(choices=[('MIN', 'Minute'), ('HOU', 'Hour'), ('DAY', 'Day'), ('WEE', 'Week'), ('MON', 'Month'), ('FDD', 'First Day'), ('FWK', 'First Week Day'), ('FWD', 'First Weekend Day'), ('LDD', 'Last Day'), ('LWK', 'Last Week Day'), ('LWD', 'Last Weekend Day')], help_text='Specify the frequency of the trigger.', max_length=3),
        ),
    ]
