# Generated by Django 3.0.3 on 2020-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_v021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(default='Unknown', editable=False, help_text='Indicates the status of the bot.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbot',
            name='status',
            field=models.CharField(default='Unknown', editable=False, help_text='Indicates the status of the bot.', max_length=255),
        ),
    ]
