# Generated by Django 3.0.3 on 2020-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_v022_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailimaptrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailoutlooktrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='filetrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalapitrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailimaptrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailoutlooktrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfiletrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalscheduletrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalsmtpaccount',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the SMTP account.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduletrigger',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the trigger.', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='status',
            field=models.CharField(default='Active', editable=False, help_text='Indicates the status of the SMTP account.', max_length=255),
        ),
    ]
