# Generated by Django 3.0.3 on 2020-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_v022_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='run_after',
            field=models.TimeField(blank=True, help_text='Specify a time to limit the bot to only be active after this time.', null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='run_on_week_days',
            field=models.BooleanField(default=True, help_text='Specify whether the bot should be active on week days.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='run_on_weekend_days',
            field=models.BooleanField(default=True, help_text='Specify whether the bot should be active on weekend days.'),
        ),
        migrations.AddField(
            model_name='bot',
            name='run_until',
            field=models.TimeField(blank=True, help_text='Specify a time to limit the bot to only be active before this time.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbot',
            name='run_after',
            field=models.TimeField(blank=True, help_text='Specify a time to limit the bot to only be active after this time.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbot',
            name='run_on_week_days',
            field=models.BooleanField(default=True, help_text='Specify whether the bot should be active on week days.'),
        ),
        migrations.AddField(
            model_name='historicalbot',
            name='run_on_weekend_days',
            field=models.BooleanField(default=True, help_text='Specify whether the bot should be active on weekend days.'),
        ),
        migrations.AddField(
            model_name='historicalbot',
            name='run_until',
            field=models.TimeField(blank=True, help_text='Specify a time to limit the bot to only be active before this time.', null=True),
        ),
    ]
