# Generated by Django 3.0.6 on 2020-05-12 09:25

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_v033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsmtpaccount',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Specify the password of the SMTP account. If the SMTP account does not require authentication, leave the password blank.<br>IMPORTANT: Remember to re-enter the password every time you edit the SMTP account.', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Specify the password of the SMTP account. If the SMTP account does not require authentication, leave the password blank.<br>IMPORTANT: Remember to re-enter the password every time you edit the SMTP account.', max_length=255),
        ),
    ]
