# Generated by Django 3.2.9 on 2021-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0010_v035'),
    ]

    operations = [
        migrations.AddField(
            model_name='botflow',
            name='is_file',
            field=models.BooleanField(default=True, help_text='Specify whether the botflow is a path to a file that the app should run or a (list of) command argument(s).'),
        ),
        migrations.AddField(
            model_name='botflowexecution',
            name='is_file',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbotflow',
            name='is_file',
            field=models.BooleanField(default=True, help_text='Specify whether the botflow is a path to a file that the app should run or a (list of) command argument(s).'),
        ),
        migrations.AlterField(
            model_name='botflow',
            name='completed_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is completed. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='botflow',
            name='error_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow fails. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'. IMPORTANT: This will not include errors during the execution of the botflow.", max_length=255),
        ),
        migrations.AlterField(
            model_name='botflow',
            name='queued_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is queued. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='botflow',
            name='started_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is started. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbotflow',
            name='completed_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is completed. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbotflow',
            name='error_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow fails. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'. IMPORTANT: This will not include errors during the execution of the botflow.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbotflow',
            name='queued_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is queued. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbotflow',
            name='started_notification',
            field=models.CharField(blank=True, help_text="Specify who (if any) should receive an email notification when the botflow is started. To specify multiple emails, use comma to separate them like this: 'abc@email.dk, xyz@email.dk'.", max_length=255),
        ),
    ]
